
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


lovelace:
  dashboards:
    minimalist-dashboard:
      mode: yaml
      title: Smart Home
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/minimalist-dashboard.yaml
